// Event endpoint
GET http://localhost:5002/api/event
###

GET http://localhost:5002/api/event/1
###

POST http://localhost:5002/api/event
AdminOnly: true
Content-Type: application/json

{
    "title": "Test",
    "date": "31-10-2024",
    "start_time": "9:30",
    "end_time": "10:00",
    "location": "Rotterdam",
    "admin_approval": true
}
###

PUT http://localhost:5002/api/event/1
AdminOnly: true
Content-Type: application/json

{
    "id": 1,
    "title": "Test Post",
    "date": "31-10-2024",
    "start_time": "9:30",
    "end_time": "11:00",
    "location": "Breda",
    "admin_approval": true
}
###

DELETE http://localhost:5002/api/event/2
AdminOnly: true
###