### Voeg een nieuwe gebruiker toe
POST http://localhost:5002/api/AddUser
Content-Type: application/json

{
    "FirstName": "Henk",
    "LastName": "Tenk",
    "Password": "Kutjes",
    "Email": "lekker@mail.com",
    "RecurringDays": 5,
    "IsAdmin": false
}